### ISSUE TITLE
odt plugin interaction enhancement

### ISSUE THREAD

**Issue by lodwicz** [LarsGit223/dokuwiki-plugin-mimeTeX#1]
Hello!

I am new to DokuWiki and PHP, and I found that your math plugin is easier to install and runs faster than the full LaTeX one (https://www.dokuwiki.org/plugin:latex). I'd like to know if you can make it work with the odt plugin (https://www.dokuwiki.org/plugin:odt) so that the odt may include the generated equations, as the LaTeX plugin tries to do.

Apparently, the trick consists in adding a case in the render() function in syntax.php, to define a new behavior when interacting with the odt plugin. You may see an example in the latexinc.php file from the LaTeX plugin https://github.com/marklundeberg/dokuwiki-plugin-latex. 

Cheers,

**Comment by lpaulsen93** [comment]
Hi,

I just changed the plugin and opened a pull-request. Hopefully the changes will be merged soon. I changed the following:
- Added ODT support
- Added support for Linux operating system

If you do not like to wait, you can checkout my patch from https://github.com/LarsGit223/dokuwiki-plugin-mimeTeX.git.

Greetings,
Lars

**Comment by MichaelGr** [comment]
Hello
Unfortunately, I have no ability to update the plugin.
Thank you Lars for operational support :-)
Regards
Michael

**Comment by lpaulsen93** [comment]
Hello jlrn7,

Michael has just merged the pull-request.

I de-installed mimetex on my installation and re-installed it from the public master repository. It seems to work fine so far, XHTML and ODT rendering.

But I am running DokuWiki on Ubuntu Linux. Could you please test if the Windows installation works fine? Once you have confirmed that it works, we can possibly close this issue.

@MichaelGr :
You wrote: 

> Unfortunately, I have no ability to update the plugin

What do you mean? It is already updated through the merge.

Regards,
Lars

**Comment by lodwicz** [comment]
The plugin seems to work fine on Win7 (32/64). Thanks.

**Comment by MichaelGr** [comment]
Thanks to Lars, this problem has been solved
