### ISSUE TITLE
Old version

### ISSUE THREAD

**Issue by lpaulsen93** [LarsGit223/dokuwiki-plugin-mimeTeX#5]
Would you mind to increase the version/to publish a new release? So everyone can notice the update.

**Comment by MichaelGr** [comment]
Hello LarsGit223
I have a counter offer to you - do you want to take the plugin for your care?
I have long abandoned this plugin and, unfortunately, there is no time to support it - everything goes to the family and the main job ((

**Comment by lpaulsen93** [comment]
Well I won't add any features to it as it just seems to work. But I can do the maintenance job. Do you want to pass ownership to me or do you prefer that I fork it? Both would be fine for me.

At any time: if you want to take it back I'll be glad to do so.

**Comment by lpaulsen93** [comment]
I have adopted the plugin. The version is up-to-date.
